name: Docker Image CI

on:
  push:
    branches: [ "main","dev" ]
  pull_request:
    branches: [ "main" ]

jobs:

  
  build:
     
    runs-on: ubuntu-latest
    
    environment:
      name: someip-docker
      
    steps:
    - name: Check out the repo
      uses: actions/checkout@v4
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push conan and cmake Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./v2x_cc/Dockerfile
        push: true
        tags: "chao123/jlr_v2x_cc:latest"

        
